[package]
name = "bobcoin-privacy"
version = "0.1.3"
edition = "2024"

[dependencies]
bulletproofs = "5.0.0"
curve25519-dalek = { version = "4.1.3", features = ["serde"] }
merlin = "3.0.0"
rand = "0.8.5"
sha2 = "0.10.9"
serde = { version = "1.0", features = ["derive"] }
