[workspace]
resolver = "2"
members = [
    "bobcoin-core",
    "bobcoin-consensus",
    "bobcoin-privacy",
    "bobcoin-dance",
    "bobcoin-node",
    "bobcoin-economy",
    "bobcoin-mining", "bobcoin-networking", "bobcoin-oracle",
]
